GET http://localhost:3003/api/blogs
###
POST http://localhost:3003/api/login
Content-Type: application/json

{
	"username": "stena",
	"password": "password"
}
###
POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN0ZW5hIiwiaWQiOiI2NzdhZmNjNWZkMWJlNzI0MGU1MWZiNjYiLCJpYXQiOjE3MzYxMTczODJ9.o88dBZobCV9P5Z18G6DiXPdIGfuvCYEuu750zaaG-Hk

{
	"title": "Delete this",
	"author": "Tena",
	"url": "http://url",
	"likes": 4
}
###
DELETE  http://localhost:3003/api/blogs/677b0ca17e2f8e3f8ea91031 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN0ZW5hIiwiaWQiOiI2NzdhZmNjNWZkMWJlNzI0MGU1MWZiNjYiLCJpYXQiOjE3MzYxMTczODJ9.o88dBZobCV9P5Z18G6DiXPdIGfuvCYEuu750zaaG-Hk
###
GET http://localhost:3003/api/blogs