GET http://localhost:3003/api/users
###
POST http://localhost:3003/api/users HTTP/1.1
content-type: application/json

{
    "username": "stena",
    "name": "Santiago Tena",
    "password": "password"
}
###
POST http://localhost:3003/api/users HTTP/1.1
content-type: application/json

{
    "username": "bhernandez",
    "name": "Blanca Hernandez",
    "password": "password2"
}
###
GET http://localhost:3003/api/users